[package]
name = "cozywitchcraft/anti-wallhop"
description = "Patches wallhopping from the humanoid controller"
version = "0.1.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["assets"]

[dependencies]
