[package]
name = "cozywitchcraft/anti-wallhop"
description = "Patches wallhopping out of the humanoid controller"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
